name: parkditto
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  slide_to_act: ^2.0.1
  intl: ^0.18.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  url_launcher: ^6.1.10
  sensors_plus: ^6.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user_location.png
    - assets/logoo.png
    - assets/ub.png
    - assets/back.png
    - assets/cara.png
    - assets/car_pin.png
    - assets/carb.png
    - assets/carz.png
    - assets/search.png
    - assets/notif.png
    - assets/motor.png
    - assets/search.png
    - assets/minitruck.png
    - assets/parkingbg.png
    - assets/farmlae_parking.png
    - assets/cctv_icon.png
    - assets/victoria.png
    - assets/bay.png
    - assets/calauan.png
    - assets/pamilihan.png
    - assets/caretaker_icon.png
    - assets/insurance_icon.png
    - assets/carwash_icon.png
    - assets/storm_icon.png
    - assets/gcash_icon.png
    - assets/paymaya_icon.png
    - assets/qr_icon.png
    - assets/parkditto_icon.png
    - assets/messenger_icon.png
    - assets/bank_icon.png
    - assets/back_icon.png
    - assets/checkMark_icon.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FDF7D887" # Optional: set background color
  adaptive_icon_foreground: "assets/logo.png" # For adaptive icons